config/routes.rb
Reservester::Application.routes.draw do
  get "pages/home"
  devise_for :owners 
  get "/restaurants/page" => "restaurants#page"
  root to: 'restaurants#index'

  resources :owners do
    resources :restaurants
  end
  
  resources :restaurants do
    resources :reservations
  end

  

  

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :restaurants, dependent: :destroy
  has_many :reservations, through: :restaurants
  validates :name, presence: true
  validates :email, presence: true
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  	validates :email, presence: true
 	# validates :requested_date, presence: true  
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :owner
	mount_uploader :menu, MenuUploader
	has_many :reservations
	validates :name, presence: true
	#validates :owner_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def create
		@restaurant=Restaurant.find(params[:restaurant_id])
		@reservation=@restaurant.reservations.create(post_reservation)
		redirect_to :back
	end


private
	def post_reservation
		params.require(:reservation).permit(:email, :requested_date, :message )
	end

	 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_filter :authenticate_owner!, only: [:new, :create]
  before_filter :confirm_owner, only: [:edit, :update, :destroy]
  
  def index
    @restaurants = Restaurant.all
  end
  
  def new   
    @restaurant = Restaurant.new
  end
  
  def create
    @restaurant = current_owner.restaurants.build(params_restaurant)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render action: "new" 
    end
  end
  
  def show
  	@restaurant = Restaurant.find(params[:id])
    @reservation = @restaurant.reservations.build
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(params_restaurant)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  def page
      @names = Restaurant.find_all_by_name(params[:search_string])
      @search_string=params[:search_string]
  end
  
private
  def params_restaurant
    params.require(:restaurant).permit(:name, :description, :full_address, :phone_number, :image, :menu, :remote_image_url)
  end


  def confirm_owner
    restaurant = Restaurant.find(params[:id])
    if restaurant.owner != current_owner
      redirect_to :back, flash: {:alert =>"you don't own this restaurant"}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">	
	<ul>
		<li>About</li>
		<li>help</li>
		<li>About</li>
		<li>&copy;2013. All rights reserved by Steve Lim.</li> 
	</ul>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
	<div class="nav_size">
		<%= link_to "Home", root_path, class: "btn-lg"  %>
		<%= link_to "New Post", new_restaurant_path, class: "btn-lg" %>
		<% if current_owner %>
			<%= link_to "Sign Out", destroy_owner_session_path, method: :delete, class: "btn-lg" %>
		<% else %>
			<%= link_to "Log In", new_owner_session_path, class: "btn-lg" %>
			<%= link_to "Sign Up", new_owner_registration_path, class: "btn-lg" %>
		<% end %>
		<span style="text-align: center">
			<%= form_tag restaurants_page_path do %>
			<%= text_field_tag :search_string %>
			<%= submit_tag "search your spot" %>
			<% end %>
		</span>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservester</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render '/layouts/header' %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>	
	<%= yield %>
	<%= render '/layouts/footer' %>	
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</body>
</html>

app/views/pages/home.html.erb
<h1 class="hero-unit">Welcome</h1>
<h3 class="center">Book & Pick your <span style="color: #ffb2b2">favorite</span> spot <small>very easy | just click | comfortable...</small></h3>

app/views/reservations/_form.html.erb
<h2>Reserve your table via email:</h2>
	<form role="form">
	<%= form_for([@restaurant,@restaurant.reservations.build]) do |f| %>
	 <p class="form-group">
	 	<%= f.label :email %>
	 	<%= f.text_field :email, placeholder: "email" %>
	 </p>
	 <p class="form-group">
	 	<%= f.label :select_date %>
	 	<%= f.date_select :requested_date %>
	 <p>	
	 <p>
	 	<%= f.label :message %>  
	 	<%= f.text_area :message, :cols=>30, :rows=> 7 %>  
	 </P> 	
	 <p>
	 	<%= f.submit "Reservation Msg", class: "btn btn-lg btn-primary" %>
	 </p>	
		<% end %> 
	</form>

app/views/restaurants/_form.html.erb
<form role="form">
	<%= form_for @restaurant, :html => {:multipart => true} ,data: {validate: 'parsley'} do |f| %>
	<p class="form-group lg">
		<h3><%= f.label :name %><br></h3>
		<%= f.text_field :name, placeholder: 'name', class: "form-control"  %>
	</P>
	<p class="form-group">
		<h3><%= f.label :description %></h3>
		<%= f.text_area :description, placeholder: 'description', class: "form-control" %>
	</P>
	<p class="form-group">
		<h3><%= f.label :full_address %><br></h3>	
		<%= f.text_area :full_address, placeholder: 'full address', class: "form-control" %>
	</p>
	<p class="form-group">
		<h3><%= f.label :phone_number %></h3>
		<%= f.text_field :phone_number, placeholder: 'phone number', :'data-type' => 'digits', class: "form-control"  %>
	</p>
	<p>
	<%= image_tag(@restaurant.image_url) if @restaurant.image? %>
		<%= f.file_field :image %>
		<%= f.hidden_field :image_cache %>	
		<br>
	
	<%= f.submit class: "btn btn-info" %>
	<% end %>
	</p>
</form>	

app/views/restaurants/_right.html.erb
<div class="right">
	Date: <div id="datepicker"></div>
	<h3>Get promo code:</h3>
</div>

app/views/restaurants/_top.html.erb
<div class="top">	
	<h1 class="center">Book & Pick your <span style="color: #ffb2b2">favorite</span> spot <small>very easy | just click | comfortable...</small></h1>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit the restaurant</h1>
<hr>
<%= render "form" %>
<%= link_to "Back", restaurants_path %>

app/views/restaurants/index.html.erb
	
<div class="container">
	<section>
		<%= render "top" %>
	</section>	
	
	<section class="main">
		<% @restaurants.each do |restaurant| %>
	
		<div class="picture">
			<%= link_to image_tag(restaurant.image.thumbnail.url, class: "smaller"),restaurant_path(restaurant) %>
	  		<button class="btn btn-info btn-lg">Poke me</button>
	  			
 		</div> <!-- /.picture -->
  		<% end %>
		<div id="dropbox"></div>
  		
	</section>

	<aside class="aside-right">
		<%= render "right" %>
	</aside>
	<section>
		<span style="margin-right:40px">
			<h3><%= link_to "New Restaurant", new_restaurant_path %></h3>
		</span>
	</section>	
</div>	

app/views/restaurants/new.html.erb
<div class="container">
	<section class="main">
		<h2>New Restaurant:</h2>
		<%= render "form" %>
		
		<h1><%= link_to "Back", restaurants_path %></h1>
	</section>	
</div>

app/views/restaurants/page.html.erb
<h1 class="center">The Search list: <span style="color: #ffb2b2"><%= @search_string %></span></h1>

app/views/restaurants/show.html.erb
	
<div class="container">
	
	<section class="column">			
			<%= image_tag @restaurant.image.masthead.url if @restaurant.image%>
			<span class="accent">Name</span>: <%= @restaurant.name %><br>
			<span class="accent">Description</span>: <%= @restaurant.description %><br>
			<span class="accent">Full Address</span>:<%= @restaurant.full_address %><br>
			<span class="accent">Menu</span>:<%= @restaurant.menu %><br>
		
			<% if @restaurant.owner %>
				<p><%= @restaurant.owner.email %></p>
				<p><%= @restaurant.owner.name %></p>
			<% end %>
			<% if current_owner == @restaurant.owner %>
				<%= link_to "Edit", edit_restaurant_path(@restaurant) %>
				<%= link_to "Destroy", restaurant_path(@restaurant), method: :delete, data: {confirm: "Are you sure you want to delete this restaurant?" } %>
			<% end %>
			<%= link_to "Back", restaurants_path, class: "btn btn-primary btn-lg" %>
	</section>
	<section class="column">
		<%= render "reservations/form" %>	
	</section>					
		
	<section class="column">
		<h2>reservation</h2>
		<% @restaurant.reservations.each do |reservation| %>
		  <p>
		    <strong>Email:</strong>
		    <%= reservation.email %>
		  </p> 
		  <p>
		    <strong>Reservation Note:</strong>
		    <%= reservation.message %>
		  </p>
		<% end %>
	</section><!--reservation container -->
	<section class="column">
		<img src="http://maps.googleapis.com/maps/api/staticmap?center=New+York,NY&zoom=13&size=600x300&key={AIzaSyC1iwgqU6etjiU7FIqPViR6lGCKGf3dKOE}&senseor=false" />
	</section>	
</div> <!-- div container -->